export const GET_DATA_REQUEST="GET_DATA_REQUEST"
export const GET_DATA_FAILURE="GET_DATA_FAILURE"

export const GET_DATA_SUCCESS="GET_DATA_SUCCESS"
export const PATCH_PRODUCT_SUCCESS="PATCH_PRODUCT_SUCCESS"
export const POST_ADD_SUCCESS="POST_ADD_SUCCESS"